[package]
edition = "2021"
name = "embassy-boot"
version = "0.1.0"
description = "Bootloader using Embassy"

[lib]

[dependencies]
defmt = { version = "0.3", optional = true }
log = { version = "0.4", optional = true  }
embassy-util = { version = "0.1.0", path = "../../embassy-util" }
embedded-storage = "0.3.0"
embedded-storage-async = "0.3.0"

[dev-dependencies]
log = "0.4"
env_logger = "0.9"
rand = "0.8"
futures = { version = "0.3", features = ["executor"] }
