[package]
name = "max30102-driver"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
biquad = { version = "0.5", default-features = false }
embassy-time = { version = "0.5.0", path = "../../embassy-time", features = ["defmt"] }
embedded-hal-async = "1.0"
defmt = "1.0.1"
