[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace MSPM0G5187 with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --restore-unwritten --verify --chip MSPM0G5187 --protocol=swd"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"
