[package]
name = "scoped-mutex"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = { version = "1.1", optional = true }

[features]
default = [
    "impl-critical-section",
]
impl-critical-section = ["dep:critical-section"]
