[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "xtask"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
xshell = "0.1"
yaml-rust = "0.4"
walkdir = "2.3.2"