[package]
edition = "2021"
name = "rp-bootloader-example"
version = "0.1.0"
description = "Example bootloader for RP2040 chips"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
defmt = { version = "1.0.1", optional = true }
defmt-rtt = { version = "1.0.0", optional = true }

embassy-rp = { path = "../../../../embassy-rp", features = ["rp2040"] }
embassy-boot-rp = { path = "../../../../embassy-boot-rp" }
embassy-sync = { version = "0.7.1", path = "../../../../embassy-sync" }
embassy-time = { path = "../../../../embassy-time", features = [] }

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = { version = "0.7" }
embedded-storage = "0.3.1"
embedded-storage-async = "0.4.0"
cfg-if = "1.0.0"

[features]
defmt = [
    "dep:defmt",
    "dep:defmt-rtt",
    "embassy-boot-rp/defmt",
    "embassy-rp/defmt",
]

[profile.release]
debug = true
opt-level = 's'

[package.metadata.embassy]
build = [
  { target = "thumbv6m-none-eabi" }
]
