[package]
edition = "2021"
name = "embassy-mspm0-c1104-examples"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]
embassy-mspm0 = { version = "0.1.0", path = "../../embassy-mspm0", features = ["mspm0c1104dgs20", "defmt", "rt", "time-driver-any"] }
embassy-executor = { version = "0.8.0", path = "../../embassy-executor", features = ["arch-cortex-m", "executor-thread", "executor-interrupt"] }
embassy-sync = { version = "0.7.1", path = "../../embassy-sync", features = ["defmt"] }
embassy-time = { version = "0.4.0", path = "../../embassy-time", features = ["defmt"] }
panic-halt = "1.0.0"
cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = { version = "0.7.0"}
defmt = "1.0.1"
defmt-rtt = "1.0.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
panic-semihosting = "0.6.0"

# The chip only has 1KB of ram, so we must optimize binaries regardless
[profile.dev]
debug = 0
opt-level = "z"
lto = true
codegen-units = 1
# strip = true

[profile.release]
debug = 0
opt-level = "z"
lto = true
codegen-units = 1
