[package]
name = "embassy-std"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[dependencies]
embassy = { version = "0.1.0", path = "../embassy", features = ["std", "time-tick-32768hz"] }
embassy-macros = { version = "0.1.0", path = "../embassy-macros", features = ["std"]}
lazy_static = "1.4.0"
