[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace stm32u083mctx with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip stm32u083mctx"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"
