[package]
name = "embassy-stm32"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[features]
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]

f4 = []
f401 = ["f4"]
f405 = ["f4"]
f407 = ["f4"]
f410 = ["f4"]
f411 = ["f4"]
f412 = ["f4"]
f413 = ["f4"]
f415 = ["f4"]
f417 = ["f4"]
f423 = ["f4"]
f427 = ["f4"]
f429 = ["f4"]
f437 = ["f4"]
f439 = ["f4"]
f446 = ["f4"]
f469 = ["f4"]
f479 = ["f4"]

[dependencies]
embassy = { version = "0.1.0", path = "../embassy" }
embassy-macros = { version = "0.1.0", path = "../embassy-macros" }
embassy-extras = {version = "0.1.0", path = "../embassy-extras" }

defmt = { version = "0.2.0", optional = true }
log = { version = "0.4.11", optional = true }
cortex-m-rt = "0.6.13"
cortex-m = "0.7.1"
embedded-hal    = { version = "0.2.4" }
futures = { version = "0.3.5", default-features = false, features = ["async-await"] }
stm32-metapac = { path = "../../stm32-metapac"}
