[package]
name = "gen_features"
version = "0.1.0"
authors = ["CÃ´me ALLART <come.allart@netc.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
yaml-rust = "0.4.5"
