[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --restore-unwritten --verify --chip mspm0g3107 --protocol=swd"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"
