[package]
name = "embassy-nrf"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[features]
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]

52810 = ["nrf52810-pac", "nrf52810-hal"]
52811 = ["nrf52811-pac"] #, "nrf52811-hal"]
52832 = ["nrf52832-pac", "nrf52832-hal"]
52833 = ["nrf52833-pac", "nrf52833-hal"]
52840 = ["nrf52840-pac", "nrf52840-hal"]


[dependencies]
embassy = { version = "0.1.0", path = "../embassy" }

anyfmt = { version = "0.1.0", path = "../anyfmt" }
defmt = { version = "0.1.0", optional = true }

cortex-m-rt = "0.6.12"
cortex-m        = { version = "0.6.3" }
embedded-hal    = { version = "0.2.4" }
bare-metal = { version = "0.2.0", features = ["const-fn"] }

nrf52810-pac  = { version = "0.9.0", optional = true }
nrf52811-pac  = { version = "0.9.1", optional = true }
nrf52832-pac  = { version = "0.9.0", optional = true }
nrf52833-pac  = { version = "0.9.0", optional = true }
nrf52840-pac  = { version = "0.9.0", optional = true }

nrf52810-hal  = { version = "0.11.0", optional = true }
#nrf52811-hal  = { version = "0.11.0", optional = true }  # doesn't exist yet
nrf52832-hal  = { version = "0.11.0", optional = true }
nrf52833-hal  = { version = "0.11.0", optional = true }
nrf52840-hal  = { version = "0.11.0", optional = true }
