[package]
name = "embassy-nrf"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[features]

# Reexport the PAC for the currently enabled chip at `embassy_nrf::pac`.
# This is unstable because semver-minor (non-breaking) releases of embassy-nrf may major-bump (breaking) the PAC version.
# If this is an issue for you, you're encouraged to directly depend on a fixed version of the PAC.
# There are no plans to make this stable.
unstable-pac = []

defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]

nrf52805 = ["nrf52805-pac"]
nrf52810 = ["nrf52810-pac"]
nrf52811 = ["nrf52811-pac"]
nrf52820 = ["nrf52820-pac"]
nrf52832 = ["nrf52832-pac"]
nrf52833 = ["nrf52833-pac"]
nrf52840 = ["nrf52840-pac"]


[dependencies]
embassy = { version = "0.1.0", path = "../embassy", features = ["time-tick-32768hz"] }
embassy-macros = { version = "0.1.0", path = "../embassy-macros", features = ["nrf"]}
embassy-hal-common = {version = "0.1.0", path = "../embassy-hal-common" }

defmt = { version = "0.2.0", optional = true }
log = { version = "0.4.11", optional = true }
cortex-m-rt = ">=0.6.15,<0.8"
cortex-m = "0.7.1"
embedded-hal    = { version = "0.2.4" }
embedded-dma    = { version = "0.1.2" }
futures     = { version = "0.3.5", default-features = false }
critical-section = "0.2.1"
rand_core = "0.6.3"

nrf52805-pac  = { version = "0.10.1", optional = true, features = [ "rt" ]}
nrf52810-pac  = { version = "0.10.1", optional = true, features = [ "rt" ]}
nrf52811-pac  = { version = "0.10.1", optional = true, features = [ "rt" ]}
nrf52820-pac  = { version = "0.10.1", optional = true, features = [ "rt" ]}
nrf52832-pac  = { version = "0.10.1", optional = true, features = [ "rt" ]}
nrf52833-pac  = { version = "0.10.1", optional = true, features = [ "rt" ]}
nrf52840-pac  = { version = "0.10.1", optional = true, features = [ "rt" ]}
