
# cargo-vet audits file

[[audits.autocfg]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.5.0"

[[audits.cc]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.2.47"

[[audits.cfg-if]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.4"

[[audits.cordyceps]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.3.4"

[[audits.darling]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.20.11"

[[audits.darling_core]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.20.11"

[[audits.darling_macro]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.20.11"

[[audits.defmt-rtt]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.0"
notes = "defmt-rtt is used for all our logging purposes. Version 1.0.0 merely stabilizes what was already available previously."

[[audits.defmt-rtt]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
delta = "1.0.0 -> 1.1.0"

[[audits.document-features]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.12"

[[audits.document-features]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-run"
version = "0.2.12"

[[audits.embassy-executor]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.9.1"

[[audits.embassy-executor-macros]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.7.0"

[[audits.embassy-executor-timer-queue]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0"

[[audits.embassy-executor-timer-queue]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0"

[[audits.embassy-time-queue-utils]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.3.0"

[[audits.find-msvc-tools]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.5"

[[audits.generator]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.8.7"

[[audits.ident_case]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.1"

[[audits.litrs]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.0"

[[audits.maitake-sync]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.2"

[[audits.mutex-traits]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.1"

[[audits.mycelium-bitfield]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.5"

[[audits.once_cell]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.20.1"

[[audits.panic-probe]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.0"

[[audits.pin-project]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.1.10"

[[audits.pin-project-internal]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.1.10"

[[audits.portable-atomic]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.11.1"

[[audits.proc-macro2]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.103"

[[audits.quote]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.42"

[[audits.stable_deref_trait]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.2.1"

[[audits.static_cell]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-run"
delta = "2.1.0 -> 2.1.1"

[[audits.syn]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "2.0.110"

[[audits.syn]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
delta = "2.0.100 -> 2.0.109"

[[audits.thiserror]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "2.0.17"

[[audits.thiserror-impl]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "2.0.17"

[[audits.unicode-ident]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.22"

[[audits.valuable]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.1"

[[trusted.aho-corasick]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-28"
end = "2026-11-26"

[[trusted.cc]]
criteria = "safe-to-deploy"
user-id = 55123 # rust-lang-owner
start = "2022-10-29"
end = "2026-11-26"

[[trusted.find-msvc-tools]]
criteria = "safe-to-deploy"
user-id = 539
start = "2025-08-29"
end = "2026-11-26"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 55123 # rust-lang-owner
start = "2024-08-15"
end = "2026-11-26"

[[trusted.loom]]
criteria = "safe-to-deploy"
user-id = 6741 # Alice Ryhl (Darksonn)
start = "2021-04-12"
end = "2026-11-26"

[[trusted.memchr]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-07"
end = "2026-11-26"

[[trusted.paste]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-19"
end = "2026-11-26"

[[trusted.regex-automata]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-25"
end = "2026-11-26"

[[trusted.regex-syntax]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-30"
end = "2026-11-26"

[[trusted.rustversion]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-07-08"
end = "2026-11-26"

[[trusted.scoped-tls]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-02-26"
end = "2026-11-26"

[[trusted.thread_local]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-09-07"
end = "2026-11-26"

[[trusted.tracing-subscriber]]
criteria = "safe-to-deploy"
user-id = 10 # Carl Lerche (carllerche)
start = "2025-08-29"
end = "2026-11-26"

[[trusted.valuable]]
criteria = "safe-to-deploy"
user-id = 10 # Carl Lerche (carllerche)
start = "2022-01-03"
end = "2026-11-26"

[[trusted.windows]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-01-15"
end = "2026-11-26"

[[trusted.windows-collections]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2025-02-06"
end = "2026-11-26"

[[trusted.windows-core]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2026-11-26"

[[trusted.windows-future]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2025-02-10"
end = "2026-11-26"

[[trusted.windows-implement]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-01-27"
end = "2026-11-26"

[[trusted.windows-interface]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-02-18"
end = "2026-11-26"

[[trusted.windows-link]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-07-17"
end = "2026-11-26"

[[trusted.windows-numerics]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2023-05-15"
end = "2026-11-26"

[[trusted.windows-result]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-02-02"
end = "2026-11-26"

[[trusted.windows-strings]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-02-02"
end = "2026-11-26"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2026-11-26"

[[trusted.windows-threading]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2025-04-29"
end = "2026-11-26"
