
# cargo-vet audits file

[[audits.autocfg]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.5.0"

[[audits.darling_core]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.20.11"

[[audits.defmt-rtt]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.0"
notes = "defmt-rtt is used for all our logging purposes. Version 1.0.0 merely stabilizes what was already available previously."

[[audits.embassy-executor-timer-queue]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0"

[[audits.embassy-executor-timer-queue]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0"

[[audits.embassy-time-queue-utils]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.3.0"

[[audits.static_cell]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-run"
delta = "2.1.0 -> 2.1.1"
