[package]
name = "embassy-net-examples"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[dependencies]
heapless            = { version = "0.5.6", default-features = false } 
embassy             = { version = "0.1.0", features=["std", "log"] }
embassy-std         = { version = "0.1.0" }
embassy-net         = { version = "0.1.0", path = "../embassy-net", features=["std", "log"] }
env_logger = "0.8.2"
log = "0.4.11"
futures = "0.3.8"
libc = "0.2.81"
async-io = "1.3.1"
smoltcp = { version = "0.6.0", default-features = false }
