[target.thumbv6m-none-eabi]
# runner = 'probe-rs run --chip STM32WL55JC --catch-hardfault --always-print-stacktrace'
runner = 'probe-rs run --chip STM32WL55JC --catch-hardfault --always-print-stacktrace'

[build]
target = "thumbv6m-none-eabi" # Cortex-M0+

[env]
DEFMT_LOG = "info"
