[package]
name = "embassy-net"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"


[package.metadata.embassy_docs]
src_base = "https://github.com/embassy-rs/embassy/blob/embassy-net-v$VERSION/embassy-net/src/"
src_base_git = "https://github.com/embassy-rs/embassy/blob/master/embassy-net/src/"
features = [ "tcp", "dhcpv4", "medium-ethernet", "medium-ip", "embassy/time", "embassy/time-tick-1mhz"]
flavors = [
    { name = "default", target = "thumbv7em-none-eabihf" },
]

[features]
default = []
std = []

defmt = ["dep:defmt", "smoltcp/defmt"]

tcp = ["smoltcp/socket-tcp"]
dhcpv4 = ["medium-ethernet", "smoltcp/socket-dhcpv4"]
medium-ethernet = ["smoltcp/medium-ethernet"]
medium-ip = ["smoltcp/medium-ip"]

pool-4 = []
pool-8 = []
pool-16 = []
pool-32 = []
pool-64 = []
pool-128 = []

[dependencies]

defmt = { version = "0.3", optional = true }
log = { version = "0.4.14", optional = true }

embassy             = { version = "0.1.0", path = "../embassy" }

managed             = { version = "0.8.0", default-features = false, features = [ "map" ] }
heapless            = { version = "0.7.5", default-features = false }
as-slice            = "0.2.1"
generic-array       = { version = "0.14.4", default-features = false }
stable_deref_trait  = { version = "1.2.0", default-features = false }
futures             = { version = "0.3.17", default-features = false, features = [ "async-await" ] }
atomic-pool = "0.2.1"

[dependencies.smoltcp]
version = "0.8.0"
default-features = false
features = [
  "proto-ipv4",
  "socket",
  "async",
]
