[package]
name = "embassy-net"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[features]
std = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

tcp = ["smoltcp/socket-tcp"]
dhcpv4 = ["medium-ethernet", "smoltcp/socket-dhcpv4"]
medium-ethernet = ["smoltcp/medium-ethernet"]
medium-ip = ["smoltcp/medium-ip"]

[dependencies]

defmt = { version = "0.2.0", optional = true }
log = { version = "0.4.11", optional = true }

embassy             = { version = "0.1.0", path = "../embassy" }

managed             = { version = "0.8.0", default-features = false, features = [ "map" ]}
heapless            = { version = "0.7.1", default-features = false }
as-slice            = { version = "0.1.4" }
generic-array       = { version = "0.14.4", default-features = false }
stable_deref_trait  = { version = "1.2.0", default-features = false }
futures             = { version = "0.3.5", default-features = false, features = [ "async-await" ]}
atomic-pool = "0.2.0"

[dependencies.smoltcp]
git = "https://github.com/smoltcp-rs/smoltcp"
rev = "ec59aba5e10cf91df0c9253d9c2aca4dd143d2ff"
default-features = false
features = [
  "proto-ipv4",
  "socket",
  "async",
]
