[package]
name = "embassy-net"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[features]
default = ["pool-4"]
std = []

tcp = ["smoltcp/socket-tcp"]
dhcpv4 = ["medium-ethernet", "smoltcp/socket-dhcpv4"]
medium-ethernet = ["smoltcp/medium-ethernet"]
medium-ip = ["smoltcp/medium-ip"]

pool-4 = []
pool-8 = []
pool-16 = []
pool-32 = []

[dependencies]

defmt = { version = "0.3", optional = true }
log = { version = "0.4.14", optional = true }

embassy             = { version = "0.1.0", path = "../embassy" }

managed             = { version = "0.8.0", default-features = false, features = [ "map" ] }
heapless            = { version = "0.7.5", default-features = false }
as-slice            = "0.2.1"
generic-array       = { version = "0.14.4", default-features = false }
stable_deref_trait  = { version = "1.2.0", default-features = false }
futures             = { version = "0.3.17", default-features = false, features = [ "async-await" ] }
atomic-pool = "0.2.1"

[dependencies.smoltcp]
git = "https://github.com/smoltcp-rs/smoltcp"
rev = "3644b94b82d9433313c75281fdc78942c2450bdf"
default-features = false
features = [
  "proto-ipv4",
  "socket",
  "async",
]
