[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip STM32L072CZTx"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"
