[package]
name = "embassy-traits"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[features]
std = []

[dependencies]
defmt = { version = "0.2.0", optional = true }
