[package]
name = "embassy-mcxa-examples"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = { version = "0.7" }
critical-section = "1.2.0"
defmt = "1.0"
defmt-rtt = "1.0"
embassy-embedded-hal = "0.5.0"
embassy-executor = { version = "0.9.0", features = ["arch-cortex-m", "executor-interrupt", "executor-thread"], default-features = false }
embassy-mcxa = { path = "../", features = ["defmt", "rt", "unstable-pac", "time"] }
embassy-sync = "0.7.2"
embassy-time = "0.5.0"
embassy-time-driver = "0.2.1"
embedded-io-async = "0.6.1"
heapless = "0.9.2"
panic-probe = { version = "1.0", features = ["print-defmt"] }

[profile.release]
lto = true # better optimizations
debug = 2  # enough information for defmt/rtt locations
