[package]
name = "embassy-mcxa-examples"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = { version = "0.7", features = ["set-sp", "set-vtor"] }
crc = "3.4.0"
critical-section = "1.2.0"
defmt = "1.0"
defmt-rtt = "1.0"
embassy-embedded-hal = { version = "0.5.0", path = "../../embassy-embedded-hal" }
embassy-executor = { version = "0.9.0", path = "../../embassy-executor", default-features = false }
embassy-mcxa = { version = "0.1.0", path = "../../embassy-mcxa", features = ["defmt", "unstable-pac"] }
embassy-sync = { version = "0.7.2", path = "../../embassy-sync" }
embassy-time = { version = "0.5.0", path = "../../embassy-time", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-time-driver = { version = "0.2.1", path = "../../embassy-time-driver", optional = true }
embedded-io-async = "0.7.0"
embedded-storage = "0.3.1"
heapless = "0.9.2"
panic-probe = { version = "1.0", features = ["print-defmt"] }
rand_core = "0.9"
static_cell = "2.1.1"
tmp108 = "0.4.0"

[features]
default = ["default-executor"]
default-executor = [
  "embassy-executor/arch-cortex-m",
  "embassy-executor/executor-interrupt",
  "embassy-executor/executor-thread",
]
custom-executor = [
  "embassy-mcxa/custom-executor"
]

[profile.release]
lto = true # better optimizations
debug = 2  # enough information for defmt/rtt locations

[package.metadata.embassy]
build = [
  { target = "thumbv8m.main-none-eabihf", artifact-dir = "out/examples/mcxa" }
]
