[package]
name = "embassy-usb-ncm"
version = "0.1.0"
edition = "2021"

[package.metadata.embassy_docs]
src_base = "https://github.com/embassy-rs/embassy/blob/embassy-usb-ncm-v$VERSION/embassy-usb-ncm/src/"
src_base_git = "https://github.com/embassy-rs/embassy/blob/master/embassy-usb-ncm/src/"
features = ["defmt"]
flavors = [
    { name = "default", target = "thumbv7em-none-eabihf" },
]

[dependencies]
embassy = { version = "0.1.0", path = "../embassy" }
embassy-usb = { version = "0.1.0", path = "../embassy-usb" }

defmt = { version = "0.3", optional = true }
log = { version = "0.4.14", optional = true }
