[package]
name = "embassy"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"
resolver = "2"

[package.metadata.embassy_docs]
src_base = "https://github.com/embassy-rs/embassy/blob/embassy-v$VERSION/embassy/src/"
src_base_git = "https://github.com/embassy-rs/embassy/blob/master/embassy/src/"
features = ["nightly", "defmt", "unstable-traits", "time", "time-tick-1mhz"]
flavors = [
    { name = "std",                       target = "x86_64-unknown-linux-gnu",   features = ["std"] },
    { name = "wasm",                      target = "wasm32-unknown-unknown",     features = ["wasm"] },
    { name = "thumbv6m-none-eabi",        target = "thumbv6m-none-eabi",         features = [] },
    { name = "thumbv7m-none-eabi",        target = "thumbv7m-none-eabi",         features = [] },
    { name = "thumbv7em-none-eabi",       target = "thumbv7em-none-eabi",        features = [] },
    { name = "thumbv7em-none-eabihf",     target = "thumbv7em-none-eabihf",      features = [] },
    { name = "thumbv8m.base-none-eabi",   target = "thumbv8m.base-none-eabi",    features = [] },
    { name = "thumbv8m.main-none-eabi",   target = "thumbv8m.main-none-eabi",    features = [] },
    { name = "thumbv8m.main-none-eabihf", target = "thumbv8m.main-none-eabihf",  features = [] },
]

[features]
default = []
std = ["futures/std", "time", "time-tick-1mhz", "embassy-macros/std"]
wasm = ["wasm-bindgen", "js-sys", "embassy-macros/wasm", "wasm-timer", "time", "time-tick-1mhz"]

# Enable nightly-only features
nightly = ["embedded-hal-async"]

# Implement embedded-hal 1.0 alpha and embedded-hal-async traits.
# Implement embedded-hal-async traits if `nightly` is set as well.
unstable-traits = ["embedded-hal-1"]

# Display a timestamp of the number of seconds since startup next to defmt log messages
# To use this you must have a time driver provided.
defmt-timestamp-uptime = ["defmt"]

# Enable `embassy::time` module. 
# NOTE: This feature is only intended to be enabled by crates providing the time driver implementation.
# Enabling it directly without supplying a time driver will fail to link.
time = []

# Set the `embassy::time` tick rate.
# NOTE: This feature is only intended to be enabled by crates providing the time driver implementation.
# If you're not writing your own driver, check the driver documentation to customize the tick rate.
# If you're writing a driver and your tick rate is not listed here, please add it and send a PR!
time-tick-32768hz = ["time"]
time-tick-1000hz = ["time"]
time-tick-1mhz = ["time"]

executor-agnostic = []

[dependencies]
defmt = { version = "0.3", optional = true }
log = { version = "0.4.14", optional = true }

embedded-hal-02 = { package = "embedded-hal", version = "0.2.6" }
embedded-hal-1 = { package = "embedded-hal", version = "1.0.0-alpha.8", optional = true}
embedded-hal-async = { version = "0.1.0-alpha.0", optional = true}

futures     = { version = "0.3.17", default-features = false, features = [ "cfg-target-has-atomic", "unstable" ] }
pin-project = { version = "1.0.8", default-features = false }
embassy-macros  = { version = "0.1.0", path = "../embassy-macros"}
atomic-polyfill = "0.1.5"
critical-section = "0.2.5"
heapless = "0.7.5"
cfg-if = "1.0.0"

# WASM dependencies
wasm-bindgen = { version = "0.2.76", features = ["nightly"], optional = true }
js-sys = { version = "0.3", optional = true }
wasm-timer = { version = "0.2.5", optional = true }

[target."thumbv6m-none-eabi".dependencies]
cortex-m = "0.7.3"
[target."thumbv7m-none-eabi".dependencies]
cortex-m = "0.7.3"
[target."thumbv7em-none-eabi".dependencies]
cortex-m = "0.7.3"
[target."thumbv7em-none-eabihf".dependencies]
cortex-m = "0.7.3"
[target."thumbv8m.base-none-eabi".dependencies]
cortex-m = "0.7.3"
[target."thumbv8m.main-none-eabi".dependencies]
cortex-m = "0.7.3"
[target."thumbv8m.main-none-eabihf".dependencies]
cortex-m = "0.7.3"

[dev-dependencies]
embassy = { path = ".", features = ["executor-agnostic"] }
futures-executor = { version = "0.3.17", features = [ "thread-pool" ] }
futures-test = "0.3.17"
futures-timer = "3.0.2"
futures-util = { version = "0.3.17", features = [ "channel" ] }
