[package]
name = "embassy"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"
resolver = "2"

[features]
default = []
std = ["futures/std", "embassy-traits/std"]

# Enable `embassy::time` module. 
# NOTE: This feature is only intended to be enabled by crates providing the time driver implementation.
# Enabling it directly without supplying a time driver will fail to link.
time = []

# Set the `embassy::time` tick rate.
# NOTE: This feature is only intended to be enabled by crates providing the time driver implementation.
# If you're not writing your own driver, check the driver documentation to customize the tick rate.
# If you're writing a driver and your tick rate is not listed here, please add it and send a PR!
time-tick-32768hz = ["time"]
time-tick-1000hz = ["time"]
time-tick-1mhz = ["time"]

defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

executor-agnostic = []

[dependencies]
defmt = { version = "0.2.0", optional = true }
log = { version = "0.4.11", optional = true }

cortex-m = "0.7.1"
futures     = { version = "0.3.5", default-features = false, features = [ "cfg-target-has-atomic", "unstable" ] }
pin-project = { version = "1.0.2", default-features = false }
embassy-macros  = { version = "0.1.0", path = "../embassy-macros"}
embassy-traits  = { version = "0.1.0", path = "../embassy-traits"}
atomic-polyfill  = { version = "0.1.1" }
critical-section = "0.2.1"
embedded-hal = "0.2.5"

[dev-dependencies]
embassy = { path = ".", features = ["executor-agnostic"] }
futures-executor = { version = "0.3", features = [ "thread-pool" ] }
futures-test = "0.3"
futures-timer = "0.3"
futures-util = { version = "0.3", features = [ "channel" ] }
