[package]
name = "embassy"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[features]
default = []
std = ["futures/std", "embassy-traits/std"]

time = []
time-tick-32768hz = ["time"]
time-tick-1000hz = ["time"]
time-tick-1mhz = ["time"]

defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

executor-agnostic = []

[dependencies]
defmt = { version = "0.2.0", optional = true }
log = { version = "0.4.11", optional = true }

cortex-m = "0.7.1"
futures     = { version = "0.3.5", default-features = false, features = [ "cfg-target-has-atomic", "unstable" ] }
pin-project = { version = "1.0.2", default-features = false }
embassy-macros  = { version = "0.1.0", path = "../embassy-macros"}
embassy-traits  = { version = "0.1.0", path = "../embassy-traits"}
atomic-polyfill  = { version = "0.1.1" }
critical-section = "0.2.1"
embedded-hal = "0.2.5"

# Workaround https://github.com/japaric/cast.rs/pull/27
cast = { version = "=0.2.3", default-features = false }
