[package]
edition = "2021"
name = "embassy-wasm-example"
version = "0.1.0"
license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
embassy-sync = { version = "0.7.1", path = "../../embassy-sync", features = ["log"] }
embassy-executor = { version = "0.8.0", path = "../../embassy-executor", features = ["arch-wasm", "executor-thread", "log"] }
embassy-time = { version = "0.4.0", path = "../../embassy-time", features = ["log", "wasm", ] }

wasm-logger = "0.2.0"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Document", "Element", "HtmlElement", "Node", "Window" ] }
log = "0.4.11"

[profile.release]
debug = 2

[package.metadata.embassy]
build = [
  { target = "wasm32-unknown-unknown", artifact-dir = "out/examples/wasm" }
]
