[package]
authors = ["Ulf Lilleengen <lulf@redhat.com>"]
edition = "2018"
name = "embassy-wasm-example"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
embassy = { version = "0.1.0", path = "../../embassy", features = ["log", "wasm", "nightly"] }

wasm-logger = "0.2.0"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Document", "Element", "HtmlElement", "Node", "Window" ] }
log = "0.4.11"
critical-section = "0.2.5"
