[package]
edition = "2024"
name = "embassy-stm32wba6-examples"
version = "0.1.0"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
embassy-stm32 = { version = "0.5.0", path = "../../embassy-stm32", features = [ "defmt", "stm32wba65ri", "time-driver-any", "memory-x", "exti"]  }
stm32-metapac = { version = "19", features = ["stm32wba65ri"] }
embassy-stm32-wpan = { version = "0.1.0", path = "../../embassy-stm32-wpan", features = ["defmt", "stm32wba65ri"], optional = true }
embassy-sync = { version = "0.7.2", path = "../../embassy-sync", features = ["defmt"] }
embassy-executor = { version = "0.9.0", path = "../../embassy-executor", features = ["arch-cortex-m", "executor-thread", "defmt"] }
embassy-time = { version = "0.5.0", path = "../../embassy-time", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-net = { version = "0.8.0", path = "../../embassy-net", features = ["defmt", "udp", "proto-ipv6", "medium-ieee802154", ], optional = true }
embassy-usb = { version = "0.5.1", path = "../../embassy-usb", features = ["defmt"] }
embassy-futures = { version = "0.1.2", path = "../../embassy-futures" }
embedded-sdmmc = "0.9.0"
embedded-hal-bus = "0.3.0"

defmt = "1.0.1"
defmt-rtt = "1.0.0"

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
embedded-hal = "1.0.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
heapless = { version = "0.9", default-features = false }
static_cell = "2"

[features]
default = ["ble"]
mac = ["dep:embassy-stm32-wpan", "embassy-stm32-wpan/wba_mac", "dep:embassy-net"]
ble = ["dep:embassy-stm32-wpan", "embassy-stm32-wpan/wba_ble", "embassy-stm32-wpan/ble-stack-basic", "embassy-stm32-wpan/linklayer6-ble-basic"]

[profile.release]
debug = 2

[[bin]]
name = "mac_ffd"
required-features = ["mac"]

[[bin]]
name = "ble_advertiser"
required-features = ["ble"]

[[bin]]
name = "ble_scanner"
required-features = ["ble"]

[[bin]]
name = "ble_peripheral_connect"
required-features = ["ble"]

[[bin]]
name = "ble_secure"
required-features = ["ble"]

[[bin]]
name = "ble_gatt_server"
required-features = ["ble"]

[[bin]]
name = "ble_central"
required-features = ["ble"]

[package.metadata.embassy]
build = [
  { target = "thumbv8m.main-none-eabihf", artifact-dir = "out/examples/stm32wba6" }
]
