[workspace]
resolver = "2"
members = [
    "blinky-pac",
    "blinky-hal",
    "blinky-irq",
    "blinky-async",
]

[patch.crates-io]
embassy-executor = { path = "../../../../../embassy-executor" }
embassy-stm32 = { path = "../../../../../embassy-stm32" }

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 's'
overflow-checks = false
