[package]
edition = "2024"
name = "embassy-nrf-rtos-trace-examples"
version = "0.1.0"
license = "MIT OR Apache-2.0"
publish = false

[features]
default = ["log"]
log = [
    "dep:log",
    "embassy-sync/log",
    "embassy-executor/log",
    "embassy-time/log",
    "embassy-nrf/log",
]

[dependencies]
embassy-sync = { version = "0.7.2", path = "../../embassy-sync" }
embassy-executor = { version = "0.9.0", path = "../../embassy-executor", features = ["arch-cortex-m", "executor-thread", "rtos-trace"] }
embassy-time = { version = "0.5.0", path = "../../embassy-time" }
embassy-nrf = { version = "0.9.0", path = "../../embassy-nrf", features = ["nrf52840", "time-driver-rtc1", "gpiote", "unstable-pac"] }

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
panic-probe = "1.0.0"
serde = { version = "1.0.136", default-features = false }
rtos-trace = "0.2"
systemview-target = { version = "0.2", features = ["callbacks-app", "callbacks-os", "log", "cortex-m"] }
log = { version = "0.4.17", optional = true }

[[bin]]
name = "rtos_trace"


[profile.release]
debug = 2

[package.metadata.embassy]
build = [
  { target = "thumbv7em-none-eabi", artifact-dir = "out/examples/nrf-rtos-trace" }
]
